SELECT DISTINCT ?event ?name ?property ?personName WHERE {
    ?event a dbo:Event; ?property ?value .
#    ?event rdfs:label ?label .
    ?event  foaf:name ?name .
    MINUS { ?event a dbo:SportsEvent . }
#    OPTIONAL {
          ?event dbp:date ?date .
          FILTER (?date <= "70"^^xsd:integer && ?date >= "-300"^^xsd:integer) .
#    }
    ?value rdfs:type ?type .
    FILTER (?type = dbo:Person)
    FILTER (lang(?label) = 'en')
    ?value  foaf:name ?personName .

}

PREFIX dbo: <http://dbpedia.org/ontology>
#PREFIX foaf: <http://xmlns.com/foaf/0.1>
#PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema>
#PREFIX owl: <http://www.w3.org/2002/07/owl>
SELECT * WHERE {
    ?event a dbo:Event .
#    ?event  foaf:name ?name .
#    MINUS { ?event a dbo:SportsEvent . }
#    ?event owl:sameAs ?sameAs .
#    ?sameAs rdfs:label ?sameAsString .
}