products:
  goethe:
    build:
      main-pkg: .
      os-archs:
      - os: darwin
        arch: amd64
      - os: linux
        arch: amd64
    dist:
      disters:
        type: os-arch-bin
        config:
          os-archs:
          - os: darwin
            arch: amd64
          - os: linux
            arch: amd64