header : |
  // Copyright (c) {{YEAR}} Parker Heindl. All rights reserved.
  //
  // Use of this source code is governed by the MIT License.
  // Read LICENSE.md in the project root for information.

