PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX bd: <http://www.bigdata.com/rdf#>
# testing
SELECT DISTINCT ?date WHERE {
    ?event wdt:P31 wd:Q178561 .
    ?event wdt:P585 ?date .
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en" .
    }
} LIMIT 10